-- Create profiles table
CREATE TABLE profiles (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  full_name TEXT,
  bio TEXT,
  role TEXT,
  contact_info JSONB,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Create vessels_gallery table
CREATE TABLE vessels_gallery (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image_url TEXT NOT NULL,
  vessel_name TEXT NOT NULL,
  description TEXT,
  year INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Create experience_logs table
CREATE TABLE experience_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company TEXT NOT NULL,
  role TEXT NOT NULL,
  vessel_type TEXT,
  start_date DATE,
  end_date DATE,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE vessels_gallery ENABLE ROW LEVEL SECURITY;
ALTER TABLE experience_logs ENABLE ROW LEVEL SECURITY;

-- Create policies
-- Profiles: Public read, Owner update
CREATE POLICY "Public profiles are viewable by everyone" ON profiles
  FOR SELECT USING (true);

CREATE POLICY "Users can update own profile" ON profiles
  FOR UPDATE USING (auth.uid() = id);

-- Vessels Gallery: Public read, Authenticated insert/update/delete
CREATE POLICY "Vessel gallery is viewable by everyone" ON vessels_gallery
  FOR SELECT USING (true);

CREATE POLICY "Authenticated users can insert vessels" ON vessels_gallery
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can update vessels" ON vessels_gallery
  FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can delete vessels" ON vessels_gallery
  FOR DELETE USING (auth.role() = 'authenticated');

-- Experience Logs: Public read, Authenticated insert/update/delete
CREATE POLICY "Experience logs are viewable by everyone" ON experience_logs
  FOR SELECT USING (true);

CREATE POLICY "Authenticated users can insert experience" ON experience_logs
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can update experience" ON experience_logs
  FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can delete experience" ON experience_logs
  FOR DELETE USING (auth.role() = 'authenticated');
