// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 01/12/2025, 17:46:59
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/bruno/Documents/GitHub/landingpage-jose/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/bruno/Documents/GitHub/landingpage-jose/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/bruno/Documents/GitHub/landingpage-jose/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/bruno/Documents/GitHub/landingpage-jose/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/bruno/Documents/GitHub/landingpage-jose/plugins/**/*.{js,ts,mjs}","C:/Users/bruno/Documents/GitHub/landingpage-jose/composables/**/*.{js,ts,mjs}","C:/Users/bruno/Documents/GitHub/landingpage-jose/utils/**/*.{js,ts,mjs}","C:/Users/bruno/Documents/GitHub/landingpage-jose/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/bruno/Documents/GitHub/landingpage-jose/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/bruno/Documents/GitHub/landingpage-jose/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/bruno/Documents/GitHub/landingpage-jose/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;