-- 1. Create albums table
CREATE TABLE albums (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable RLS on albums
ALTER TABLE albums ENABLE ROW LEVEL SECURITY;

-- 3. Create policies for albums (same as other tables)
CREATE POLICY "Public albums are viewable by everyone." ON albums FOR SELECT USING (true);
CREATE POLICY "Users can insert their own albums." ON albums FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Users can update their own albums." ON albums FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Users can delete their own albums." ON albums FOR DELETE USING (auth.role() = 'authenticated');

-- 4. Migrate existing data: Insert distinct album titles from vessels_gallery
INSERT INTO albums (title)
SELECT DISTINCT album_title FROM vessels_gallery;

-- 5. Add album_id column to vessels_gallery
ALTER TABLE vessels_gallery ADD COLUMN album_id BIGINT REFERENCES albums(id) ON DELETE CASCADE;

-- 6. Update vessels_gallery with correct album_id
UPDATE vessels_gallery vg
SET album_id = a.id
FROM albums a
WHERE vg.album_title = a.title;

-- 7. Make album_id NOT NULL (optional, but good for integrity if all rows matched)
-- ALTER TABLE vessels_gallery ALTER COLUMN album_id SET NOT NULL;

-- 8. Drop the old album_title column
ALTER TABLE vessels_gallery DROP COLUMN album_title;
