-- Create certifications table
CREATE TABLE certifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL,
  description_pt TEXT NOT NULL,
  description_en TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable RLS
ALTER TABLE certifications ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Certifications are viewable by everyone" ON certifications
  FOR SELECT USING (true);

CREATE POLICY "Authenticated users can insert certifications" ON certifications
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can update certifications" ON certifications
  FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can delete certifications" ON certifications
  FOR DELETE USING (auth.role() = 'authenticated');

-- Seed Data (Exemplos)
INSERT INTO certifications (code, description_pt) VALUES
('TBS I', 'Treinamento Básico de Segurança'),
('EBPQ', 'Especial para Básico de Proteção de Navio'),
('CESS', 'Curso Especial de Sobrevivência e Salvamento'),
('ESOP', 'Especial de Operações de Carga em Navios Petroleiros'),
('CIR', 'Caderneta de Inscrição e Registro');
